# Generated by Django 5.1.6 on 2025-02-10 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('num_habitaciones', models.PositiveIntegerField()),
                ('tipo_alojamiento', models.CharField(choices=[('hotel', 'Hotel'), ('hostal', 'Hostal'), ('casa_rural', 'Casa Rural')], default='hotel', max_length=50)),
                ('website', models.URLField(blank=True, null=True)),
                ('horario_checkin', models.TimeField(blank=True, null=True)),
                ('horario_checkout', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escapada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('familiar', 'Familiar'), ('amigos', 'Con amigos'), ('corporativa', 'Corporativa')], max_length=50)),
                ('num_plazas', models.PositiveIntegerField()),
                ('num_inscritos', models.PositiveIntegerField(default=0)),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('lugar', models.CharField(max_length=200)),
                ('url_formulario_inscripcion', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='escapadas/')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='abierta', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EscapadaAlojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alojamientos_escapada', to='mi_app.alojamiento')),
                ('escapada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escapadas_alojamiento', to='mi_app.escapada')),
            ],
            options={
                'unique_together': {('escapada', 'alojamiento')},
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('capacidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('suite', 'Suite')], default='individual', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='disponible', max_length=20)),
                ('escapada_alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='mi_app.escapadaalojamiento')),
            ],
            options={
                'unique_together': {('escapada_alojamiento', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('alojamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.alojamiento')),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mi_app.habitacion')),
            ],
        ),
    ]
