# Generated by Django 5.1.6 on 2025-02-19 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254)),
                ('num_habitaciones', models.PositiveIntegerField()),
                ('tipo_alojamiento', models.CharField(choices=[('hotel', 'Hotel'), ('hostal', 'Hostal'), ('casa_rural', 'Casa Rural')], default='hotel', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='alojamientos/')),
                ('website', models.URLField(blank=True, null=True)),
                ('horario_checkin', models.TimeField(blank=True, null=True)),
                ('horario_checkout', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alojamiento',
            },
        ),
        migrations.CreateModel(
            name='Escapada',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('universitarios', 'Universitarios'), ('profesionales', 'Profesionales'), ('senior', 'Senior')], max_length=50)),
                ('num_plazas', models.PositiveIntegerField(blank=True, null=True)),
                ('num_inscritos', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('fecha_ini', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=200, null=True)),
                ('url_formulario_inscripcion', models.URLField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='escapadas/')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='cerrada', max_length=20)),
            ],
            options={
                'db_table': 'escapada',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=150, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pagado', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('sexo', models.CharField(blank=True, max_length=20, null=True)),
                ('prefijo', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('es_pringado', models.BooleanField(default=False)),
                ('anio_pringado', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_alojamiento_deseado', models.CharField(blank=True, max_length=100, null=True)),
                ('num_familiares', models.PositiveIntegerField(blank=True, null=True)),
                ('es_anfitrion', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.CreateModel(
            name='EscapadaAlojamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alojamientos_escapada', to='mi_app.alojamiento')),
                ('escapada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escapadas_alojamiento', to='mi_app.escapada')),
            ],
            options={
                'db_table': 'escapadaalojamiento',
                'unique_together': {('escapada', 'alojamiento')},
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_pagado', models.BooleanField(default=False)),
                ('tipo_habitacion_preferida', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_inscripcion', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('importe_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('es_anfitrion', models.BooleanField(default=False)),
                ('escapada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='mi_app.escapada')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='mi_app.persona')),
            ],
            options={
                'db_table': 'inscripcion',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ficticio', models.CharField(blank=True, max_length=50, null=True)),
                ('numero', models.CharField(max_length=20, null=True)),
                ('capacidad', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('triple', 'Triple'), ('cuadruple', 'Cuádruple'), ('quintuple', 'Quíntuple'), ('sextuple', 'Sextuple'), ('septuple', 'Septuple')], default='individual', max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada')], default='disponible', max_length=20)),
                ('reservado_hasta', models.DateTimeField(blank=True, null=True)),
                ('escapada_alojamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='mi_app.escapadaalojamiento')),
                ('reservado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitaciones_reservadas', to='mi_app.persona')),
            ],
            options={
                'db_table': 'habitacion',
                'unique_together': {('escapada_alojamiento', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.habitacion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_app.persona')),
            ],
            options={
                'db_table': 'reservahabitacion',
                'unique_together': {('persona', 'habitacion')},
            },
        ),
    ]
