# Generated by Django 5.1.6 on 2025-02-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='alojamientos/'),
        ),
    ]
