# Generated by Django 5.1.6 on 2025-02-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_alojamiento_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escapada',
            name='tipo',
            field=models.CharField(choices=[('universitarios', 'Universitarios'), ('profesionales', 'Profesionales'), ('senior', 'Senior')], max_length=50),
        ),
    ]
