# Generated by Django 5.1.6 on 2025-02-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_remove_inscripcion_es_anfitrion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='es_anfitrion',
        ),
    ]
