# Generated by Django 5.1.6 on 2025-02-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0003_alter_escapada_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escapada',
            name='estado',
            field=models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='cerrada', max_length=20),
        ),
        migrations.AlterField(
            model_name='escapada',
            name='url_formulario_inscripcion',
            field=models.URLField(blank=True, null=True),
        ),
    ]
