# Generated by Django 5.1.6 on 2025-02-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_inscripcion_checkin_completado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='anio_pringado',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
