# Generated by Django 5.1.6 on 2025-02-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_alter_escapada_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escapada',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
