# Generated by Django 5.1.6 on 2025-02-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_alter_escapada_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escapada',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escapada',
            name='fecha_ini',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='escapada',
            name='lugar',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='escapada',
            name='num_inscritos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='escapada',
            name='num_plazas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
