# Generated by Django 5.1.6 on 2025-02-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_alter_persona_anio_pringado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='anio_pringado',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
