# Generated by Django 5.1.6 on 2025-02-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0006_alter_persona_anio_pringado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('reservada', 'Reservada'), ('bloqueada', 'Bloqueada')], default='disponible', max_length=20),
        ),
    ]
