# Generated by Django 5.1.6 on 2025-02-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0008_alter_habitacion_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='estado',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
